## signals(features)

convert lines, words, x, y, w, h in html input tag into singals

In [27]:
def count_line(contents):
    if not contents: 
        return 0
    lines = contents.split('\n')
    return len(lines)

def mean_word(contents):
    if not contents: 
        return 0
    lines = contents.split('\n')
    words = [len(line.split(' ')) for line in lines]
    return np.mean(words)

def total_word(contents):
    if not contents:
        return 0
    lines = contents.split('\n')
    words = [len(line.split(' ')) for line in lines]
    return sum(words)

def std_w(data_w):
    if not data_w:
        return 0
    ws = map(int, data_w.split(','))
    return np.std(ws)

def mean_y(data_y):
    if not data_y:
        return 0
    ys = map(int, data_y.split(','))
    return np.mean([abs(ys[1:][i] - ys[:-1][i]) for i in range(0, len(ys[1:]))])

def mean_h(data_h):
    if not data_h:
        return 0
    hs = map(int, data_h.split(','))
    return np.mean(hs)

def mean_x(data_x):
    if not data_x:
        return 0
    xs = map(int, data_x.split(','))
    x_min = np.min(xs)
    return np.mean(map(lambda x:x-x_min, xs))

def get_page(page):
    return int(page.replace('Page', '').strip())

In [28]:
def convert_feature(df, target=1):
    df['count_line'] = df['content'].apply(count_line)
    df['mean_word'] = df['content'].apply(mean_word)
    df['total_word'] = df['content'].apply(total_word)
    df['std_w'] = df['data_w'].apply(std_w)
    df['mean_y'] = df['data_y'].apply(mean_y)
    df['mean_h'] = df['data_h'].apply(mean_h)
    df['mean_x'] = df['data_x'].apply(mean_x)
    df['page_num'] = df['page'].apply(get_page)
    df['target'] = target
    return df


## Read poem

In [29]:
import numpy as np
import pandas as pd

poems = pd.read_csv('../data/poem-austlit-20160412.csv')
convert_feature(poems, target=1)
print poems.shape

(500, 10)


title  \
0                            Poets Corner   
1                          CORRESPONDENCE   
2                         The Worshipper.   
3                      THE LOST MERCHANT.   
4                         ENIGMA.—No. IV.   
5                             "Pioneers."   
6                        Original Poetry.   
7                  Grandmother's Mission.   
8                       Literary Matters.   
9                  THE CHILDREN'S CORNER.   
10                        Original Poetry   
11                   GOD SAVE THE PRINCE.   
12                           Poets Cornes   
13                        OLD FAVOURITES.   
14             The Traveller Trudging By.   
15                           JENNY AND I.   
16                                SECOND.   
17                       Love's Ministry.   
18   To the Editor of the Sydney Gazette.   
19                       ORIGINAL POETRY.   
20               One Faith in Many Forms.   
21                          A True Lover.   
22                             ARK DOINGS   
23                         Tags of Verse.   
24                             THE TWINS.   
25                                  LIFE.   
26                                ENIGMA.   
27                        YE CITY GUARDS.   
28                               LITERARY   
29                    OUR HEART'S DESIRE.   
..                                    ...   
470                       The Fleet Sails   
471                               Poetry.   
472                           Advertising   
473                    THE POETS' CORNER.   
474                              STANZAS.   
475                      ORIGINAL POETRY.   
476                               LADIES.   
477                 Queensland To Britain   
478                               Echoes.   
479                      IN LIGHTER VEIN.   
480                              BODALLA.   
481                              Charley.   
482                      Original Poetry.   
483                      Original poetry.   
484              POEMS BY CHARLES HARPUR.   
485                    THE POETS' CORNER.   
486            Notes for town and Country   
487                            LITERATURE   
488                      BETSY IN DANGER.   
489                               POETRY.   
490                     Literary Matters.   
491                        Tags of Terse.   
492                     If You Were Here.   
493                          THE RACES O.   
494                                MUSIC.   
495                            LITERATURE   
496                           Advertising   
497                               ENIGMA.   
498   THE RAIN COMBS SOBBING TO THE DOOR.   
499                           Advertising   

                                                data_h  \
0    144,308,78,30,42,36,36,39,37,40,38,36,38,38,39...   
1    61,61,48,39,32,43,39,41,38,39,33,39,36,40,39,4...   
2    55,37,40,32,34,30,30,35,35,35,28,30,34,30,32,2...   
3    41,56,35,29,28,26,27,26,27,25,26,25,27,26,25,2...   
4    32,38,36,37,38,32,38,38,37,35,38,39,41,37,33,3...   
5    67,37,34,39,37,44,38,43,36,43,37,43,37,44,35,4...   
6    56,61,50,55,62,41,41,47,47,43,49,41,42,85,43,4...   
7    51,47,47,43,50,48,47,48,48,49,46,51,47,50,49,4...   
8    85,31,41,30,41,38,37,41,38,40,40,43,41,42,35,3...   
9    70,56,47,50,55,57,57,55,45,49,48,42,53,52,54,5...   
10   49,40,65,74,70,53,63,94,50,28,61,53,116,60,62,...   
11                       46,31,37,38,41,42,36,40,35,37   
12   37,542,36,36,41,39,41,38,35,37,34,41,36,35,42,...   
13   40,24,29,31,30,31,30,31,28,28,31,26,29,28,26,3...   
14   42,37,33,39,37,40,39,39,39,33,33,37,37,37,38,4...   
15   26,26,24,26,23,28,26,25,26,28,26,25,23,26,28,2...   
16   42,37,43,40,39,39,44,36,42,35,40,34,43,40,44,3...   
17   69,60,45,44,52,43,41,41,55,63,45,41,61,39,44,4...   
18   50,41,37,52,51,53,53,51,46,52,63,46,49,50,53,4...   
19   29,69,47,39,44,40,46,31,62,45,55,48,51,48,68,5...   
20   74,38,56,56,53,55,56,5

In [30]:
# others
others = pd.read_csv('../data/others-201604120925.csv')
convert_feature(others, target=0)
print others.shape

(493, 10)


C:\Users\uqbjeon\AppData\Local\Continuum\Miniconda2\envs\myenv\lib\site-packages\numpy\core\_methods.py:59: RuntimeWarning: Mean of empty slice.
  warnings.warn("Mean of empty slice.", RuntimeWarning)


title  \
0                                 THE FREETRADE CAUSE.   
1                BUSINESS AT THE CENTRAL POLICE COURT.   
2                              INTERCOLONIAL SHIPPING.   
3                                     NEWS OF THE DAY.   
4                                          PARRAMATTA.   
5                                      SYDNEY MARKETS.   
6                                          Advertising   
7                                          Advertising   
8                         To the Editor of the Herald.   
9              SCOTTISH AND AUSTRALIAN MINING COMPANY.   
10                          PUBLIC MEETING AT PENRITH.   
11                               UNIVERSITY OF SYDNEY.   
12                        TO THE EDITOR OF THE HERALD.   
13        LORD WILLOUGHBY AND THE COUNTESS D'ALTEYRAC.   
14                                             MEXICO.   
15                                PUGILISM IN ENGLAND.   
16                                         Advertising   
17                                   CONTINENTAL NEWS.   
18                            INDEX TO ADVERTISEMENTS.   
19                 RAILWAY FROM TARAGO TO BUN GENDORE.   
20                        COASTERS OUTWARDS.—MARCH 15.   
21                                          MELBOURNE.   
22    ALL-ENGLAND ELEVEN V. TWENTY-TWO OF THE MARYB...   
23                                    BROUGH COUNCILS.   
24                                         SCHEDULE A.   
25                               LEGISLATIVE ASSEMBLY.   
26                                   EXPORTS.—JULY 20.   
27                       MERCANTILE AND MONEY ARTICLE.   
28                                           SHIPPING.   
29                    CUSTOMS IMPORT ENTRIES.—JUNE 29.   
..                                                 ...   
463                                          OFFICIAL.   
464                                        Advertising   
465                      MELBOURNE LIVE STOCK REPORTS.   
466               MOB RULE—TOWN HALL—FRIDAY'S MEETING.   
467                    WINDS AND WEATHER.—FEBRUARY 16.   
468                                    WILD WEST SHOW.   
469                             MEETINGS OF COMPANIES.   
470                                WATER POLICE COURT.   
471                                         THE MAILS.   
472                                        Advertising   
473                                 MANAGERS' REPORTS.   
474                             (FROM BOARD AT TELE[?]   
475                                          SHIPPING.   
476                                            PARKES.   
477                                     Family Notices   
478  MEETINGS. THE MELBOURNE INTERNATIONAL EXHIBITION.   
479                           MONETARY AND COMMERCIAL.   
480                                    PORT OF SYDNEY.   
481                                      THE RAILWAYS.   
482                                           ARALUEN.   
483                      CENTRAL AMATEUR RACE MEETING.   
484                                   BALMAIN REGATTA.   
485                                 EXPORTS.—MARCH 11.   
486                    THE VOLUNTEER CAMP AT RICHMOND.   
487                            METEOROLOGICAL REPORTS.   
488                             THE STEAMSHIP AORANGI.   
489                                        CASUALTIES.   
490  NEW SOUTH WALES PARLIAMENT. LEGISLATIVE ASSEMBLY.   
491                                        Advertising   
492                                PICKINGS FROM JUDY.   

                                                data_h  \
0    23,49,28,27,32,32,28,26,31,28,29,27,30,27,28,3...   
1    36,43,37,39,40,39,40,40,39,35,41,41,41,40,36,2...   
2    37,33,35,34,32,34,33,37,34,36,28,35,36,34,34,3...   
3    30,19,38,31,35,34,36,33,36,32,36,36,37,37,38,3...   
4    31,43,30,34,34,33,34,40,29,35,37,38,37,38,34,3...   
5    38,28,31,28,27,28,27,30,27,28,34,27,29,28,33,3...   
6                              27,30,27,29,31,

In [42]:
all_df = pd.concat([poems, others])

In [43]:
all.shape

(993, 19)

In [44]:
from __future__ import division

import numpy as np
import operator

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.cross_validation import cross_val_score, KFold

from sklearn.naive_bayes import MultinomialNB, BernoulliNB
from sklearn.svm import SVC
from sklearn.linear_model import SGDClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

from sklearn import metrics
from sklearn.grid_search import GridSearchCV
from sklearn.pipeline import Pipeline

from sklearn.base import BaseEstimator
from sklearn.base import ClassifierMixin
from sklearn.preprocessing import LabelEncoder
from sklearn.externals import six
from sklearn.base import clone
from sklearn.pipeline import _name_estimators


In [169]:
class MajorityVoteClassifier(object):
    def __init__(self):
        self.classifiers = []
        self.weights = None

    def read_files(self):
        poems = pd.read_csv('../data/poem-austlit-20160412.csv')
        convert_feature(poems, target=1)
        others = pd.read_csv('../data/poem-austlit-20160412.csv')
        convert_feature(others, target=0)
        
    def process_data(self, df):
        format_features = ['count_line', 'mean_word', 'total_word', 'std_w', 'mean_y', 'mean_h', 'mean_x', 'page_num']
        content_features = 'content'
        y_feature = ['target']
        
        X_format = df[format_features].values
        X_format[X_format > 1000] = 1000
        X_format[np.isnan(X_format)] = 0
        self.X_format = X_format
        
        X_content = df[content_features].values
        X_content = CountVectorizer(max_df=10, min_df=1).fit_transform(X_content)
        X_content = TfidfTransformer().fit_transform(X_content)
        self.X_content = X_content
        
        y = df[y_feature].values
        y = y.flatten()
        self.y = y
        
    def predict(self):
        row_count, _ = self.X_format.shape
        test_count = 100
        idx = np.random.randint(0, row_count, test_count)
        X_format = self.X_format[idx]
        X_content = self.X_content[idx]
        print(X_format)
        print(X_content)
        print self.y
        print(idx)
        y = self.y[idx]
        print(y)
        
        predictions = [self._predict(self.X_format[i, :], self.X_content[i, :])  for i in range(0, test_count)]
        predictions = np.array(predictions)
        print(predictions)
        print(y)
        print(sum(predictions==y)/test_count)
        return sum(predictions==y)/test_count
    
    def _predict(self, X_format, X_content):
        return self.predict_proba(X_format, X_content)
    
    def predict_proba(self, X_format, X_content):
        probas = []
        print("%%%%%%%%%%%%%%%%%%%%%%%%%%%")
        for name, clf in self.classifiers:
            print(name)
            if name == 'RandomForestClassifier':
                probas.append(clf.predict_proba(X_format))
                p1 = clf.predict(X_format)
                print(clf.predict_proba(X_format), clf.predict(X_format))
            else:
                probas.append(clf.predict_proba(X_content))
                p2 = clf.predict(X_content)
                print(clf.predict_proba(X_content), clf.predict(X_content))
        
        probas = np.asarray(probas)
        n = np.argmax(probas)
        
        print n

        if n in [0, 1]:
            return p1[0]
        return p2[0]
    
    def train(self, df):
        print('train *************************************')
        self.train_df = df
        print('process_data ******************************')
        self.process_data(df)
        print('triain_rfclassifier ***********************')
        self.triain_rfclassifier()
        print('triain_nbclassifier ***********************')
        self.triain_nbclassifier()
        print('predict ***********************************')
        print self.predict()
        
    def triain_rfclassifier(self):
        X, y = self.X_format, self.y
        clf = Pipeline([#('pca', PCA()),
                    ('clf', RandomForestClassifier()),
                ])

        parameters = {#'pca__n_components': (3, 4, 5, 6, 7),
#                         'clf__n_estimators': (5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 60, 70), 
#                         'clf__criterion': ('gini', 'entropy'),
#                         'clf__max_features': ('auto', 'sqrt', 'log2')
                     }    

        gs_clf = GridSearchCV(clf, parameters, cv=5)
        gs_clf.fit(X, y)

        best_parameters, score, _ = max(gs_clf.grid_scores_, key=lambda x: x[1])
        print('RandomForestClassifier')
        print('Score : ', score)
        for param_name in sorted(parameters.keys()):
            print("%s: %r" % (param_name, best_parameters[param_name]))
        
#         self.best_rfc = gs_clf.best_estimator_
        self.classifiers.append(('RandomForestClassifier', gs_clf.best_estimator_))
    
    def triain_nbclassifier(self):
        X, y = self.X_content, self.y
        clf = Pipeline([
                        ('clf', MultinomialNB()),
                    ])

        parameters = { 'clf__alpha': (0,1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4), 
                        'clf__fit_prior':(True, False)}    

        gs_clf = GridSearchCV(clf, parameters, cv=5)
        gs_clf.fit(X, y)

        best_parameters, score, _ = max(gs_clf.grid_scores_, key=lambda x: x[1])
        print('MultinomialNB')
        print('Score : ', score)
        for param_name in sorted(parameters.keys()):
            print("%s: %r" % (param_name, best_parameters[param_name]))
        
#         self.best_nbc = gs_clf.best_estimator_
        self.classifiers.append(('MultinomialNB', gs_clf.best_estimator_))
        
    

In [170]:
mvc = MajorityVoteClassifier()
mvc.train(all_df)

train *************************************
process_data ******************************
triain_rfclassifier ***********************
RandomForestClassifier
('Score : ', 0.89023162134944611)
triain_nbclassifier ***********************
MultinomialNB
('Score : ', 0.90634441087613293)
clf__alpha: 0.3
clf__fit_prior: False
predict ***********************************
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 

C:\Users\uqbjeon\AppData\Local\Continuum\Miniconda2\envs\myenv\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Users\uqbjeon\AppData\Local\Continuum\Miniconda2\envs\myenv\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Users\uqbjeon\AppData\Local\Continuum\Miniconda2\envs\myenv\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape

(array([[ 0.00770972,  0.99229028]]), array([1], dtype=int64))
1
%%%%%%%%%%%%%%%%%%%%%%%%%%%
RandomForestClassifier
(array([[ 0.,  1.]]), array([1], dtype=int64))
MultinomialNB
(array([[ 0.03688694,  0.96311306]]), array([1], dtype=int64))
1
%%%%%%%%%%%%%%%%%%%%%%%%%%%
RandomForestClassifier
(array([[ 0.,  1.]]), array([1], dtype=int64))
MultinomialNB
(array([[ 0.0148179,  0.9851821]]), array([1], dtype=int64))
1
%%%%%%%%%%%%%%%%%%%%%%%%%%%
RandomForestClassifier
(array([[ 0.,  1.]]), array([1], dtype=int64))
MultinomialNB
(array([[ 0.04666402,  0.95333598]]), array([1], dtype=int64))
1
%%%%%%%%%%%%%%%%%%%%%%%%%%%
RandomForestClassifier
(array([[ 0.,  1.]]), array([1], dtype=int64))
MultinomialNB
(array([[ 0.06173339,  0.93826661]]), array([1], dtype=int64))
1
%%%%%%%%%%%%%%%%%%%%%%%%%%%
RandomForestClassifier
(array([[ 0.,  1.]]), array([1], dtype=int64))
MultinomialNB
(array([[ 0.06491509,  0.93508491]]), array([1], dtype=int64))
1
%%%%%%%%%%%%%%%%%%%%%%%%%%%
RandomForestClassifier
(

C:\Users\uqbjeon\AppData\Local\Continuum\Miniconda2\envs\myenv\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Users\uqbjeon\AppData\Local\Continuum\Miniconda2\envs\myenv\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Users\uqbjeon\AppData\Local\Continuum\Miniconda2\envs\myenv\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape

(array([[ 0.00876387,  0.99123613]]), array([1], dtype=int64))
3
%%%%%%%%%%%%%%%%%%%%%%%%%%%
RandomForestClassifier
(array([[ 0.,  1.]]), array([1], dtype=int64))
MultinomialNB
(array([[ 0.04559916,  0.95440084]]), array([1], dtype=int64))
1
%%%%%%%%%%%%%%%%%%%%%%%%%%%
RandomForestClassifier
(array([[ 0.1,  0.9]]), array([1], dtype=int64))
MultinomialNB
(array([[ 0.03977369,  0.96022631]]), array([1], dtype=int64))
3
%%%%%%%%%%%%%%%%%%%%%%%%%%%
RandomForestClassifier
(array([[ 0.,  1.]]), array([1], dtype=int64))
MultinomialNB
(array([[ 0.04797534,  0.95202466]]), array([1], dtype=int64))
1
%%%%%%%%%%%%%%%%%%%%%%%%%%%
RandomForestClassifier
(array([[ 0.,  1.]]), array([1], dtype=int64))
MultinomialNB
(array([[ 0.02833581,  0.97166419]]), array([1], dtype=int64))
1
%%%%%%%%%%%%%%%%%%%%%%%%%%%
RandomForestClassifier
(array([[ 0.1,  0.9]]), array([1], dtype=int64))
MultinomialNB
(array([[ 0.19868498,  0.80131502]]), array([1], dtype=int64))
1
%%%%%%%%%%%%%%%%%%%%%%%%%%%
RandomForestClassi

C:\Users\uqbjeon\AppData\Local\Continuum\Miniconda2\envs\myenv\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Users\uqbjeon\AppData\Local\Continuum\Miniconda2\envs\myenv\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Users\uqbjeon\AppData\Local\Continuum\Miniconda2\envs\myenv\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape

(array([[ 0.1,  0.9]]), array([1], dtype=int64))
MultinomialNB
(array([[ 0.101501,  0.898499]]), array([1], dtype=int64))
1
%%%%%%%%%%%%%%%%%%%%%%%%%%%
RandomForestClassifier
(array([[ 0.3,  0.7]]), array([1], dtype=int64))
MultinomialNB
(array([[ 0.06626402,  0.93373598]]), array([1], dtype=int64))
3
%%%%%%%%%%%%%%%%%%%%%%%%%%%
RandomForestClassifier
(array([[ 0.,  1.]]), array([1], dtype=int64))
MultinomialNB
(array([[ 0.04771907,  0.95228093]]), array([1], dtype=int64))
1
%%%%%%%%%%%%%%%%%%%%%%%%%%%
RandomForestClassifier
(array([[ 0.,  1.]]), array([1], dtype=int64))
MultinomialNB
(array([[ 0.01369479,  0.98630521]]), array([1], dtype=int64))
1
%%%%%%%%%%%%%%%%%%%%%%%%%%%
RandomForestClassifier
(array([[ 0.,  1.]]), array([1], dtype=int64))
MultinomialNB
(array([[ 0.02271382,  0.97728618]]), array([1], dtype=int64))
1
%%%%%%%%%%%%%%%%%%%%%%%%%%%
RandomForestClassifier
(array([[ 0.4,  0.6]]), array([1], dtype=int64))
MultinomialNB
(array([[ 0.01812459,  0.98187541]]), array([1], dty

C:\Users\uqbjeon\AppData\Local\Continuum\Miniconda2\envs\myenv\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Users\uqbjeon\AppData\Local\Continuum\Miniconda2\envs\myenv\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Users\uqbjeon\AppData\Local\Continuum\Miniconda2\envs\myenv\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape

(array([[ 0.09840176,  0.90159824]]), array([1], dtype=int64))
3
%%%%%%%%%%%%%%%%%%%%%%%%%%%
RandomForestClassifier
(array([[ 0.,  1.]]), array([1], dtype=int64))
MultinomialNB
(array([[ 0.03421751,  0.96578249]]), array([1], dtype=int64))
1
%%%%%%%%%%%%%%%%%%%%%%%%%%%
RandomForestClassifier
(array([[ 0.,  1.]]), array([1], dtype=int64))
MultinomialNB
(array([[ 0.02967867,  0.97032133]]), array([1], dtype=int64))
1
%%%%%%%%%%%%%%%%%%%%%%%%%%%
RandomForestClassifier
(array([[ 0.1,  0.9]]), array([1], dtype=int64))
MultinomialNB
(array([[ 0.01519963,  0.98480037]]), array([1], dtype=int64))
3
%%%%%%%%%%%%%%%%%%%%%%%%%%%
RandomForestClassifier
(array([[ 0.,  1.]]), array([1], dtype=int64))
MultinomialNB
(array([[ 0.04237336,  0.95762664]]), array([1], dtype=int64))
1
%%%%%%%%%%%%%%%%%%%%%%%%%%%
RandomForestClassifier
(array([[ 0.,  1.]]), array([1], dtype=int64))
MultinomialNB
(array([[ 0.02026322,  0.97973678]]), array([1], dtype=int64))
1
%%%%%%%%%%%%%%%%%%%%%%%%%%%
RandomForestClassifi

C:\Users\uqbjeon\AppData\Local\Continuum\Miniconda2\envs\myenv\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Users\uqbjeon\AppData\Local\Continuum\Miniconda2\envs\myenv\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Users\uqbjeon\AppData\Local\Continuum\Miniconda2\envs\myenv\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape

(array([[ 0.03597495,  0.96402505]]), array([1], dtype=int64))
3
%%%%%%%%%%%%%%%%%%%%%%%%%%%
RandomForestClassifier
(array([[ 0.,  1.]]), array([1], dtype=int64))
MultinomialNB
(array([[ 0.06493574,  0.93506426]]), array([1], dtype=int64))
1
%%%%%%%%%%%%%%%%%%%%%%%%%%%
RandomForestClassifier
(array([[ 0.,  1.]]), array([1], dtype=int64))
MultinomialNB
(array([[ 0.05387925,  0.94612075]]), array([1], dtype=int64))
1
%%%%%%%%%%%%%%%%%%%%%%%%%%%
RandomForestClassifier
(array([[ 0.,  1.]]), array([1], dtype=int64))
MultinomialNB
(array([[ 0.02282447,  0.97717553]]), array([1], dtype=int64))
1
%%%%%%%%%%%%%%%%%%%%%%%%%%%
RandomForestClassifier
(array([[ 0.,  1.]]), array([1], dtype=int64))
MultinomialNB
(array([[ 0.01050781,  0.98949219]]), array([1], dtype=int64))
1
%%%%%%%%%%%%%%%%%%%%%%%%%%%
RandomForestClassifier
(array([[ 0.,  1.]]), array([1], dtype=int64))
MultinomialNB
(array([[ 0.02454561,  0.97545439]]), array([1], dtype=int64))
1
%%%%%%%%%%%%%%%%%%%%%%%%%%%
RandomForestClassifier

C:\Users\uqbjeon\AppData\Local\Continuum\Miniconda2\envs\myenv\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Users\uqbjeon\AppData\Local\Continuum\Miniconda2\envs\myenv\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Users\uqbjeon\AppData\Local\Continuum\Miniconda2\envs\myenv\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape

(array([[ 0.,  1.]]), array([1], dtype=int64))
MultinomialNB
(array([[ 0.05693165,  0.94306835]]), array([1], dtype=int64))
1
%%%%%%%%%%%%%%%%%%%%%%%%%%%
RandomForestClassifier
(array([[ 0.,  1.]]), array([1], dtype=int64))
MultinomialNB
(array([[ 0.00337573,  0.99662427]]), array([1], dtype=int64))
1
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[0 1 0 1 0 1 0 1 0 0 0 0 0 1 0 0 0 0 0 0 1 1 1 0 1 1 0 1 1 0 0 1 0 0 1 0 0
 1 0 1 1 1 1 0 1 0 1 1 0 0 1 1 0 1 0 1 1 0 0 1 0 1 0 1 1 0 0 1 0 1 1 1 1 1
 0 1 0 0 1 0 1 1 1 1 1 0 0 0 1 1 0 1 1 1 0 0 0 0 0 0]
0.49
0.49


C:\Users\uqbjeon\AppData\Local\Continuum\Miniconda2\envs\myenv\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Users\uqbjeon\AppData\Local\Continuum\Miniconda2\envs\myenv\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Users\uqbjeon\AppData\Local\Continuum\Miniconda2\envs\myenv\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape

## Read other articles & generate signals(features)

## Fetch signals(features) before applying algorithm

In [54]:
features = ['count_line', 'mean_word', 'total_word', 'std_w', 'mean_y', 'mean_h', 'mean_x', 'page_num', 'content']

In [55]:
other_x = others[features].values

In [56]:
other_x[other_x > 1000] = 1000
other_x[np.isnan(other_x)] = 0

In [57]:
poem_x = poems[features].values

In [58]:
X = np.concatenate((other_x, poem_x), axis=0)

In [59]:
other_y = others[['target']].values
poem_y = poems[['target']].values
y = np.concatenate((other_y, poem_y), axis=0)

In [62]:
y = y.flatten()
print X.shape, y.shape

(993L, 8L) (993L,)


In [63]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.cross_validation import cross_val_score, KFold
from sklearn import decomposition
from sklearn.metrics.pairwise import euclidean_distances
from sklearn.naive_bayes import MultinomialNB, BernoulliNB
from sklearn.svm import SVC
from sklearn.linear_model import SGDClassifier
from sklearn.cluster import KMeans, MiniBatchKMeans
from sklearn.decomposition import TruncatedSVD
from sklearn import metrics
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.grid_search import GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.decomposition import PCA

## Applying different algoriths with only newspaper format signal to check  accurcy

### 1. Applying SVC Classifier(Support Vector Machine)

In [64]:
svc = SGDClassifier()
svc.fit(X, y)
scores = cross_val_score(svc, X, y, cv=5)
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Accuracy: 0.58 (+/- 0.13)


### 2. Appliying Random Forest Classifier

In [65]:
forest = RandomForestClassifier()
forest.fit(X, y)
scores = cross_val_score(forest, X, y, cv=5)
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Accuracy: 0.91 (+/- 0.01)


### 3. Appliying Logistic Regression Classifier

In [66]:
logistic = LogisticRegression()
logistic.fit(X, y)
scores = cross_val_score(logistic, X, y, cv=5)
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Accuracy: 0.80 (+/- 0.06)


### 4. Appliying Naive Bayes Classifier

In [67]:
nb = MultinomialNB()
nb.fit(X, y)
scores = cross_val_score(nb, X, y, cv=5)
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Accuracy: 0.64 (+/- 0.09)


## Find optimization in Random Forest Classifier which is the best classifier

In [68]:
clf = Pipeline([#('pca', PCA()),
                    ('clf', RandomForestClassifier()),
                ])

parameters = {#'pca__n_components': (3, 4, 5, 6, 7),
                'clf__n_estimators': (5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 60, 70), 
                'clf__criterion': ('gini', 'entropy'),
                'clf__max_features': ('auto', 'sqrt', 'log2')
             }    

gs_clf = GridSearchCV(clf, parameters, cv=5)
gs_clf.fit(X, y)

best_parameters, score, _ = max(gs_clf.grid_scores_, key=lambda x: x[1])
print('Score : ', score)
for param_name in sorted(parameters.keys()):
    print("%s: %r" % (param_name, best_parameters[param_name]))


('Score : ', 0.93353474320241692)
clf__criterion: 'gini'
clf__max_features: 'auto'
clf__n_estimators: 70


## Find important singals  

In [69]:
clf = RandomForestClassifier(n_estimators=50, max_features='sqrt', criterion='gini')
clf.fit(X, y)

print sorted(zip(map(lambda x: round(x, 4), clf.feature_importances_), features), reverse=True)

[(0.2245, 'page_num'), (0.1505, 'mean_y'), (0.1357, 'mean_h'), (0.1252, 'mean_word'), (0.1182, 'total_word'), (0.0954, 'count_line'), (0.0934, 'mean_x'), (0.0573, 'std_w')]


#### Best signals

1. mean word per line
1. newspaper page number
1. indent x

### Apply Naive Bayes algorithm on poem and other articles

In [69]:
X = np.concatenate((poems['content'].values, others['content'].values), axis=0)
print type(X)
print X.shape
vectorizer = CountVectorizer(max_df=10, min_df=1)
X = vectorizer.fit_transform(X)
X = TfidfTransformer().fit_transform(X)
  

<type 'numpy.ndarray'>
(993L,)


In [70]:
X = all_df['content'].values
print type(X)
print X.shape
vectorizer = CountVectorizer(max_df=10, min_df=1)
X = vectorizer.fit_transform(X)
X = TfidfTransformer().fit_transform(X)

<type 'numpy.ndarray'>
(993L,)


In [71]:
nb = MultinomialNB()
nb.fit(X, y)

scores = cross_val_score(nb, X, y, cv=5)
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Accuracy: 0.91 (+/- 0.03)


In [76]:
clf = Pipeline([
#                 ('vect', CountVectorizer()),
#                 ('tfidf', TfidfTransformer()),
                ('clf', MultinomialNB()),
            ])
    
parameters = {
#                 'tfidf__use_idf': (True, False),
                'clf__alpha': (0,1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4), 
                'clf__fit_prior':(True, False)}    
    
    
gs_clf = GridSearchCV(clf, parameters, cv=5)

gs_clf.fit(X, y)

best_parameters, score, _ = max(gs_clf.grid_scores_, key=lambda x: x[1])
print('Score : ', score)
for param_name in sorted(parameters.keys()):
    print("%s: %r" % (param_name, best_parameters[param_name]))

('Score : ', 0.91339375629405839)
clf__alpha: 1
clf__fit_prior: True


### Combine the two best classifiers(RandomForest classifier on newspaper format and Naive Bayes on Content)

In [78]:
class MajorityVoteClassifier(BaseEstimator, ClassifierMixin):
    def __init__(self, classifiers, weights=None):
        self.classifiers = classifiers
        self.named_classifiers = {key: value for key, value in _name_estimators(classifiers)}
        print(self.named_classifiers)
        self.weights = weights
    
    def fit(self, X, y):
        self.classifiers_ = []
        for clf in self.classifiers:
            
            fitted_clf = clone(clf).fit(X, y)
            self.classifiers_.append(fitted_clf)
        return self

    def predict(self, X):
        return np.argmax(self.predict_proba(X), axis=1)
    
    def predict_proba(self, X):
        probas = np.asarray([cls.predict_proba(X) for clf in self.classifiers_])
        avg_proba = np.average(probas, axis=0, weights=self.weights)
        return avg_proba
    
    def get_params(self, deep=True):
        if not deep:
            return super(MajorityVoteClassifier, self).get_params(deep=False)
        else:
            out = self.named_classifiers.copy()
            for name, step in six.iteritems(self.named_classifiers):
                for key, value in six.iteritems(step.get_params(deep=True)):
                    out['%s__%s' % (name, key)] = value
            return out

In [135]:
a = [[100, 12]]
b = [[3, 4]]
c = []
c.append(a)
c.append(b)
c = np.array(c)
np.argmax(c)

0